name: subtitle_downloader
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.2+7

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  dio: ^5.9.1
  file_picker: ^10.3.10
  cr_file_saver:
    git:
      url: https://github.com/dhruvanbhalara/cr_file_saver
      ref: "fix/incorrect_file_name"
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  gap: ^3.0.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.6.2
  path_provider: ^2.1.5
  draggable_home: ^1.0.5
  readmore: ^3.0.0
  storax: ^0.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  sign_in_button: ^4.0.1
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  dartz: ^0.10.1
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/language_list.json
    - assets/icon/icon.png
    - shorebird.yaml